language: node_js
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = false ] && [ "$TRAVIS_BRANCH" = master ]; then

    echo "machine github.com\n login $GH_TOKEN" > ~/.netrc
    chmod 600 ~/.netrc

    cd build

    npm install
    cat ~/.netrc | ./node_modules/.bin/cipherhub sidorares
    ./setup.sh
    ./publish.sh
  fi
branches:
  only:
  - master
env:
  global:
    secure: QEkTHfJRxcsDLtNbLBEcbEQKyTg/uFf6BfzpZ8WqRSFX7SamsHcKpsj+TRQdpqheWUWRRksH0AX+LRN/B3/XeWEdzFygBq880LkVlnK16T1aSJ2MOBVTuA/3GYOeUJU7PaiJ+xPwThRv041li5aKF4tHZHIEflWHP1LqD5yuSLE=
