language: node_js
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = false ] && [ "$TRAVIS_BRANCH" = master ]; then

    echo "machine github.com\n login $GH_TOKEN" > ~/.netrc
    chmod 600 ~/.netrc

    cd build

    npm install
    cat ~/.netrc | ./node_modules/.bin/cipherhub sidorares
    ./setup.sh
    ./publish.sh
  fi
branches:
  only:
  - master
env:
  global:
    secure: e+rqu5DWzUV9siiguPKk3NyURXxshhp9uwWX/kgRzD3w8M41Aa71FBSS5hfkp4zmG51ZAU49++0Jar8l+otHPgYo6Ce5deRUkO0Tu0yS+h+jAfxhFqwGrPMBtb5b/I3RBALW0H3o2NWKNxZ+fD0zTFDdw+yu0+3vXtgsGpLdFug=
