language: node_js

after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = false ] && [ "$TRAVIS_BRANCH" = master ]; then

    echo "machine github.com\nlogin sidorares\npassword $GITHUB_TOKEN" > ~/.netrc
    chmod 600 ~/.netrc

    cd build
    cat ~/.netrc
    ls -al ~

    npm install
    ./setup.sh
    ./publish.sh
  fi
branches:
  only:
  - master
env:
  global:
    secure: aiPlRfZ6LtC4FPDUWI5aEj4MwVTcWIiSvl+sYKzNJBEJXPIi+wLiHcnhMsLcZXUA3XomScfrTsdiqf3+bPy3MZ2mGPQVho/X0VK6YzZ6nCuNmRoPY2TJ4wH8lQR5pW7Htng8duLV4DCiaUSiPJYvWCRv+irrZocFlfy2L6hibFo=
