language: node_js
after_success:
- |
  if [ "$TRAVIS_PULL_REQUEST" = false ] && [ "$TRAVIS_BRANCH" = master ]; then
    cd build
    cat ~/.netrc | ./node_modules/.bin/cipherhub sidorares
    ls -al ~

    npm install
    ./setup.sh
    ./publish.sh $PUBLISH_URL
  fi
branches:
  only:
  - master
env:
  global:
    secure: Az2402lBi8LTGPrdylWRrIzvgCDlz8/fyfDRZgc2+IwULcZq5F7SHUh7XzBUi4zkCtPe9nYAOQamww2OvkRv1A0oQPBzYltS5yU+TeQKQ9q9uhzMqFM+ZWSVe105e+YwuKtK4ApEsy+uZEXzSnCr2XMIxR1qB8abGUg2MJ6lT7k=
